# Generated by Django 5.2 on 2025-05-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ticket Booking', 'Ticket Booking'), ('Bill Payment', 'Bill Payment'), ('Recharge', 'Recharge'), ('Fund Transfer', 'Fund Transfer'), ('Purchase E-commerce', 'Purchase E-commerce')], max_length=50)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Wallet', 'Wallet')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
