# Generated by Django 5.2 on 2025-07-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_duenotification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenotification',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ecommercetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Ticket Booking', 'Ticket Booking'), ('Bill Payment', 'Bill Payment'), ('Recharge', 'Recharge'), ('Fund Transfer', 'Fund Transfer'), ('Purchase E-commerce', 'Purchase E-commerce')], max_length=100),
        ),
    ]
