# Generated by Django 5.2 on 2025-07-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_duenotification_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Booking For Transport', 'Booking For Transport'), ('Bill Payment', 'Bill Payment'), ('Recharge', 'Recharge'), ('Fund Transfer', 'Fund Transfer'), ('Purchase E-commerce', 'Purchase E-commerce')], max_length=100),
        ),
    ]
